<a href="https://colab.research.google.com/github/DrAlexSanz/amld-pytorch-workshop/blob/master/ALEX_1_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<div>
<img src="https://discuss.pytorch.org/uploads/default/original/2X/3/35226d9fbc661ced1c5d17e374638389178c3176.png" width="400" style="margin: 50px auto; display: block; position: relative; left: -30px;" />
</div>

<!--NAVIGATION-->
# | Basics | [Autograd >](2-Autograd.ipynb)

### Basics

In this first notebook, we will introduce Tensors, which are the base element in PyTorch.  
We will see different ways to create Tensors and check their properties. Then, we will briefly go through all the different kind of operations they support, such as mathematical operations, indexing, reshaping, expansion, masking, type conversion, etc.

### Table of Contents

#### 1. [Introduction](#Introduction)  
#### 2. [Tensor Creation](#Tensor-Creation)
#### 3. [Tensor Properties](#Tensor-Properties)  
#### 4. [Tensor Operations](#Tensor-Operations)  
#### 5. [Tensor Conversions](#Tensor-Conversions)  

---

# Introduction

### What is PyTorch ?
Python-based scientific computing library, similar to NumPy.  
Differentiates from NumPy in 3 main aspects:
- It allows to use the power of **GPU** computing
- It comes with an **automatic differentiation** module
- It is a fully-fledged **deep learning research platform**


In [0]:
import torch
import numpy as np

In [0]:
print("PyTorch Version:", torch.__version__)

PyTorch Version: 1.3.1


____

### What is a tensor?

A **matrix** is a grid of numbers, let's say (3x5).  
In simple terms, a **tensor** can be seen as a generalization of a matrix to higher dimension.  
It can be of arbitrary shape, e.g. (3 x 6 x 2 x 10). 

You can think of tensors as multidimensional arrays.

In [0]:
X = torch.tensor([1, 2, 3, 4, 5])
X

tensor([1, 2, 3, 4, 5])

In [0]:
X.shape

torch.Size([5])

In [0]:
X = torch.tensor([[1, 2, 3], [4, 5, 6]])
X

tensor([[1, 2, 3],
        [4, 5, 6]])

In [0]:
X.shape

torch.Size([2, 3])

### PyTorch vs NumPy 

`torch.tensor` behaves like `numpy.array` under mathematical operations.  
The syntax is very similar between the two libraries.  
If you are familiar with NumPy, you can [browse here](https://github.com/wkentaro/pytorch-for-numpy-users#types) to check what are NumPy functions equivalent in PyTorch.

For example:

In [0]:
np.eye (2)

array([[1., 0.],
       [0., 1.]])

In [0]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [0]:
np.arange(1,5)

array([1, 2, 3, 4])

In [0]:
torch.arange(1,5)

tensor([1, 2, 3, 4])

As we said, `torch.tensor` additionally keeps track of the computation graphs (see next notebook) and provides GPU support.

---

# Tensor Creation

In [0]:
torch.zeros((3, 5))

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [0]:
torch.ones(5)

tensor([1., 1., 1., 1., 1.])

In [0]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [0]:
torch.empty((3, 5)) #Random initialization

tensor([[1.6351e-36, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 2.8026e-45, 0.0000e+00],
        [1.1210e-44, 0.0000e+00, 1.4013e-45, 0.0000e+00, 0.0000e+00]])

In [0]:
 torch.rand((5, 3))

tensor([[0.0260, 0.5164, 0.6141],
        [0.2025, 0.9716, 0.4112],
        [0.1985, 0.9774, 0.3632],
        [0.1553, 0.1438, 0.7462],
        [0.8039, 0.9841, 0.9863]])

In [0]:
torch.arange(3, 9, 2)

tensor([3, 5, 7])

In [0]:
torch.linspace(0, 1, 11)

tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000, 1.0000])

In [0]:
A = torch.ones((2,3))
torch.zeros_like(A)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

This list is not exhaustive but gives you an idea of the diversity of way to create a Tensor

<div style="background-color:lightblue;padding:1rem;border-radius: 0.015rem 0.015rem 0.03rem 0.03rem;">
<h3 style="display: inline; font-weight:bold">Your turn!</h3>
</div>

**_Create the tensor:_**

$$ \begin{bmatrix}
5 & 7 & 9 & 11 & 13 & 15 & 17 & 19
\end{bmatrix}  $$

In [0]:
cipote = torch.arange(5, 20, step = 2)
cipote

tensor([ 5,  7,  9, 11, 13, 15, 17, 19])

<div style="background-color:lightblue;padding:1rem;border-radius: 0.03rem 0.03rem 0.015rem 0.015rem;">
<h3 style="display: inline"></h3>
</div>

---

# Tensor Properties

In [0]:
x = torch.Tensor([[0,1,2], [3,4,5]]) #The default is float32

print("x.shape: \n%s\n" % (x.shape,))
print("x.size(): \n%s\n" % (x.size(),))
print("x.size(1): \n%s\n" % x.size(1))
print("x.dim(): \n%s\n" % x.dim())
print("x.numel(): \n%s\n" % x.numel())

x.shape: 
torch.Size([2, 3])

x.size(): 
torch.Size([2, 3])

x.size(1): 
3

x.dim(): 
2

x.numel(): 
6



In [0]:
print("x.dtype: \n%s\n" % x.dtype)
print("x.device: \n%s\n" % x.device)

x.dtype: 
torch.float32

x.device: 
cpu



The `nonzero` function returns indices of the non zero elements.

In [0]:
x = torch.Tensor([[0,1,2], [3,4,5]])

print("x.nonzero(): \n%s\n" % x.nonzero())

x.nonzero(): 
tensor([[0, 1],
        [0, 2],
        [1, 0],
        [1, 1],
        [1, 2]])



---

# Tensor Operations

Unlike in NumPy, there are two ways to performs most operations in PyTorch:
 - using **`torch.op(tensor)`**
 - using **`tensor.op()`**

In [0]:
X = torch.rand(3, 2)

In [0]:
torch.exp(X)

tensor([[1.2100, 1.7435],
        [2.3398, 2.7044],
        [1.2971, 1.9891]])

In [0]:
X.exp()

tensor([[1.2100, 1.7435],
        [2.3398, 2.7044],
        [1.2971, 1.9891]])

You can easily chain operators :

In [0]:
X.sqrt().std()

tensor(0.2246)

In [0]:
(X.exp() + 2).sqrt() - 2 * X.log().sigmoid()  # be creative :-)

tensor([[1.4714, 1.2202],
        [1.1643, 1.1715],
        [1.4029, 1.1823]])

Many more functions are available: sin, cos, tanh, bmm, cumsum, dot, etc.

<div style="background-color:lightblue;padding:1rem;border-radius: 0.015rem 0.015rem 0.03rem 0.03rem;">
<h3 style="display: inline; font-weight:bold">Your turn!</h3>
</div>

Compute the norms of the row-vectors in matrix **X** without using `torch.norm()`.

Remember: $$||\vec{v}||_2 = \sqrt{x_1^2 + x_2^2 + \dots + x_n^2}$$

Hint: `X**2` computes the element-wise square.

In [0]:
X = torch.eye(4) + torch.arange(4).repeat(4, 1).float()

sol = (X**2).sum().sqrt()
sol

# SOLUTION: tensor(8.4853)

tensor(8.4853)

<div style="background-color:lightblue;padding:1rem;border-radius: 0.03rem 0.03rem 0.015rem 0.015rem;">
<h3 style="display: inline"></h3>
</div>

## Reductions

In [0]:
X = torch.rand(3, 2)
X

tensor([[0.7005, 0.0919],
        [0.4432, 0.5348],
        [0.0876, 0.3258]])

In [0]:
X.sum()

tensor(2.1838)

In [0]:
X.max()

tensor(0.7005)

In [0]:
X.mean(dim=1)

tensor([0.3962, 0.4890, 0.2067])

In [0]:
X.norm(p=1.3)

tensor(1.5311)

<div style="background-color:lightblue;padding:1rem;border-radius: 0.015rem 0.015rem 0.03rem 0.03rem;">
<h3 style="display: inline; font-weight:bold">Your turn!</h3>
</div>

For $X_{i,j}$ , compute $Y$ such that $Y_j = \log \big[ \sum_j \exp (X_{i,j}) \big]$.

In [0]:
X = torch.eye(4) + torch.arange(4).repeat(4, 1).float()
X

sol = X.exp().sum(dim = 1).log() # Order of operations is RPN!, not forward notation like in the CASIO
sol
# YOUR TURN

# SOLUTION: tensor([3.4938, 3.5797, 3.7817, 4.1852])

tensor([3.4938, 3.5797, 3.7817, 4.1852])

<div style="background-color:lightblue;padding:1rem;border-radius: 0.03rem 0.03rem 0.015rem 0.015rem;">
<h3 style="display: inline"></h3>
</div>

## Linear Algebra

In [0]:
Y = torch.rand(2, 3)

In [0]:
# Matrix multiplication
Y.t() @ Y

tensor([[0.3159, 0.6856, 0.4168],
        [0.6856, 1.4898, 0.9309],
        [0.4168, 0.9309, 1.0176]])

In [0]:
Y.t().matmul(Y) #Equivalent to the previous one

tensor([[0.3159, 0.6856, 0.4168],
        [0.6856, 1.4898, 0.9309],
        [0.4168, 0.9309, 1.0176]])

In [0]:
# CAUTION: Operator '*' does element-wise multiplication, just like in numpy!
# Y.t() * Y  # error, dimensions do not match for element-wise multiplication

In [0]:
torch.inverse(Y.t() @ Y)

tensor([[-2.9325e+07,  1.3985e+07, -7.8361e+05],
        [ 1.3985e+07, -6.6698e+06,  3.7371e+05],
        [-7.8361e+05,  3.7371e+05, -2.0937e+04]])

In [0]:
Y = torch.rand(3, 3)

In [0]:
Y.det()

tensor(-0.0282)

In [0]:
Y.eig()

torch.return_types.eig(eigenvalues=tensor([[-0.0921,  0.0000],
        [ 0.1906,  0.0000],
        [ 1.6061,  0.0000]]), eigenvectors=tensor([]))

## In-place operators (mutations)

Functions that mutate the object end with an underscore, e.g. *add_*, *div_*, etc.

In [0]:
A = torch.eye(3)
A

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [0]:
A.add(5)

tensor([[6., 5., 5.],
        [5., 6., 5.],
        [5., 5., 6.]])

In [0]:
A # VIEW

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [0]:
A.add_(5) #Inplace!

tensor([[6., 5., 5.],
        [5., 6., 5.],
        [5., 5., 6.]])

In [0]:
A

tensor([[6., 5., 5.],
        [5., 6., 5.],
        [5., 5., 6.]])

In [0]:
A.div_(3)

tensor([[2.0000, 1.6667, 1.6667],
        [1.6667, 2.0000, 1.6667],
        [1.6667, 1.6667, 2.0000]])

In [0]:
A

tensor([[2.0000, 1.6667, 1.6667],
        [1.6667, 2.0000, 1.6667],
        [1.6667, 1.6667, 2.0000]])

In [0]:
A.uniform_()  # fills the tensor with random uniform numbers in [0, 1]

tensor([[0.3696, 0.6046, 0.4665],
        [0.6424, 0.5544, 0.7214],
        [0.8453, 0.5470, 0.8729]])

In [0]:
A

tensor([[0.3696, 0.6046, 0.4665],
        [0.6424, 0.5544, 0.7214],
        [0.8453, 0.5470, 0.8729]])

#### Also note the difference:
```python
A = A + 1  # After this operation, A is a new variable and memory has been copied
A += 1     # After this operation, A stayed the same variable and memory has been changed in place
```

Compare the outputs:

In [0]:
A = torch.ones(1)

A_before = A
A = A + 1

print(A, A_before)

tensor([2.]) tensor([1.])


In [0]:
A = torch.ones(1)

A_before = A
A += 1

print(A, A_before)

tensor([2.]) tensor([2.])


## Indexing

Again, it works just like in NumPy.

In [0]:
A = torch.randint(100, (3, 3))
A

tensor([[36, 97, 79],
        [61, 91,  6],
        [ 3, 88, 18]])

In [0]:
A[0, 0]

tensor(36)

In [0]:
A[2, 1] # 0 indexing!

tensor(88)

In [0]:
A[1]

tensor([61, 91,  6])

In [0]:
A[:, 1]

tensor([97, 91, 88])

In [0]:
A[:, 1:2], A[:, 1:2].shape

(tensor([[97],
         [91],
         [88]]), torch.Size([3, 1]))

In [0]:
A[1:, :2]

tensor([[61, 91],
        [ 3, 88]])

_Note: You can use `...` to mark any number of dimension_

<div style="background-color:lightblue;padding:1rem;border-radius: 0.015rem 0.015rem 0.03rem 0.03rem;">
<h3 style="display: inline; font-weight:bold">Your turn!</h3>
</div>

In [0]:
X = torch.arange(40).view(5,8)
X

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39]])

**_Extract this vector from the tensor X:_**

$ \begin{bmatrix}
17 & 19 & 21 & 23 \\
\end{bmatrix}  $


In [0]:
# From the 2nd line, take one out of two elements starting from the second one
c = X[2, 1::2] # I never use this, but ::n is the step size
c

tensor([17, 19, 21, 23])

<div style="background-color:lightblue;padding:1rem;border-radius: 0.015rem 0.015rem 0.03rem 0.03rem;">
<h3 style="display: inline; font-weight:bold"></h3>
</div>

## Reshaping & Expanding

**`view`** is the equivalent of `reshape` in NumPy, but `view` does not allocate new memory: the output tensor shares the same data!

The number of arguments of `view` will be the number of dimensions of the output tensor.

In [0]:
X = torch.tensor([1, 2, 3, 4, 5, 6])
X

tensor([1, 2, 3, 4, 5, 6])

In [0]:
Y = X.view(2, 3)  # view tensor X on 2 dimensions, with a size 2 on dimension 1 and a size 3 on dimension 2
Y

tensor([[1, 2, 3],
        [4, 5, 6]])

In [0]:
Y = X.view(-1)  # -1 tells PyTorch to infer the number of elements along that dimension
Y, Y.shape

(tensor([1, 2, 3, 4, 5, 6]), torch.Size([6]))

In [0]:
Y = X.view(-1, 2)
Y, Y.shape

(tensor([[1, 2],
         [3, 4],
         [5, 6]]), torch.Size([3, 2]))

**`expand`** creates a new view of the tensor with dimensions of size 1 expanded to a larger size. This does not allocate new memory either !

In [0]:
Y = torch.ones(5)
Y, Y.shape

(tensor([1., 1., 1., 1., 1.]), torch.Size([5]))

In [0]:
Y = Y.view(-1, 1)
Y, Y.shape

(tensor([[1.],
         [1.],
         [1.],
         [1.],
         [1.]]), torch.Size([5, 1]))

In [0]:
Y.expand(5, 5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [0]:
X = torch.eye(4)
Y = X[3:, :]
Y, Y.shape # It's a matrix, after squeeze it's a vector. This is similar to the (3,) in python.

(tensor([[0., 0., 0., 1.]]), torch.Size([1, 4]))

`squeeze` and `unsqueeze`

In [0]:
Y = Y.squeeze()  # removes all dimensions of size '1'
Y, Y.shape

(tensor([0., 0., 0., 1.]), torch.Size([4]))

In [0]:
Y = Y.unsqueeze(1)  # add a new dimension in position 1
Y, Y.shape

(tensor([[0.],
         [0.],
         [0.],
         [1.]]), torch.Size([4, 1]))

_Note: There also exists `reshape` and `repeat` functions in PyTorch. They work similarly to `view` and `expand` but **do** copy memory_.

<div style="background-color:lightblue;padding:1rem;border-radius: 0.015rem 0.015rem 0.03rem 0.03rem;">
<h3 style="display: inline; font-weight:bold">Your turn!</h3>
</div>

**_Create the tensor:_**

$ \begin{bmatrix}
7 & 5 & 5 & 5 & 5 \\
5 & 7 & 5 & 5 & 5 \\
5 & 5 & 7 & 5 & 5 \\
5 & 5 & 5 & 7 & 5 \\
5 & 5 & 5 & 5 & 7 
\end{bmatrix}  $

Hint: You can use matrix sum and scalar multiplication

In [0]:
b = torch.eye(5) * 2 + 5
b

tensor([[7., 5., 5., 5., 5.],
        [5., 7., 5., 5., 5.],
        [5., 5., 7., 5., 5.],
        [5., 5., 5., 7., 5.],
        [5., 5., 5., 5., 7.]])

**_Create the tensor:_**

$ \begin{bmatrix}
4 & 6 & 8 & 10 & 12 \\
14 & 16 & 18 & 20 & 22 \\
24 & 26 & 28 & 30 & 32
\end{bmatrix}$

In [0]:
c = torch.arange(4, 33, step = 2) # 33 is not evaluated, it stops at end-1
c = c.view(3, -1) # I don't want to compute how many columns I need
c

tensor([[ 4,  6,  8, 10, 12],
        [14, 16, 18, 20, 22],
        [24, 26, 28, 30, 32]])

**_Create the tensor:_**

$ \begin{bmatrix}
2 & 2 & 2 & 2 & 2 \\
4 & 4 & 4 & 4 & 4 \\
6 & 6 & 6 & 6 & 6 \\
8 & 8 & 8 & 8 & 8
\end{bmatrix}  $

In [0]:
c = torch.arange(2, 9, step = 2).unsqueeze(1) # Before I expand I need to add a dimension
c = c.expand(4, 5)
c # I don't copy memory, I only have 4 values in memory that are then copied, but not stored.

tensor([[2, 2, 2, 2, 2],
        [4, 4, 4, 4, 4],
        [6, 6, 6, 6, 6],
        [8, 8, 8, 8, 8]])

<div style="background-color:lightblue;padding:1rem;border-radius: 0.015rem 0.015rem 0.03rem 0.03rem;">
<h3 style="display: inline; font-weight:bold"></h3>
</div>

## Masking

In [0]:
X = torch.randint(100, (5, 3))
X

tensor([[89, 59, 32],
        [80, 74, 11],
        [38, 62, 63],
        [59, 77, 48],
        [47, 34, 50]])

In [0]:
mask = (X > 25) & (X < 75)
mask # It's boolean masking

tensor([[False,  True,  True],
        [False,  True, False],
        [ True,  True,  True],
        [ True, False,  True],
        [ True,  True,  True]])

In [0]:
X[mask]  # returns all elements matching the criteria in a 1D-tensor

tensor([59, 32, 74, 38, 62, 63, 59, 48, 47, 34, 50])

In [0]:
mask.sum()  # number of elements that fulfill the condition

tensor(11)

In [0]:
(X == 25) | (X > 60)

tensor([[ True, False, False],
        [ True,  True, False],
        [False,  True,  True],
        [False,  True, False],
        [False, False, False]])

In [0]:
X[mask] = 0  # You can assign new values only to indices matching the condition:
X

tensor([[89,  0,  0],
        [80,  0, 11],
        [ 0,  0,  0],
        [ 0, 77,  0],
        [ 0,  0,  0]])

<div style="background-color:lightblue;padding:1rem;border-radius: 0.015rem 0.015rem 0.03rem 0.03rem;">
<h3 style="display: inline; font-weight:bold">Your turn!</h3>
</div>

In [0]:
X = torch.tensor([[1, 0, 2], [4, 6, 0]])

Get the number of non-zeros in **X**

In [0]:
mask = (X != 0).sum() # Or X.nonzero()
mask

tensor(4)

Compute the sum of all entries in **X** that are larger than the mean of all values in **X**.

In [0]:
X_p = X.float().mean()
X_p
mask = (X > X_p).sum()
mask

tensor(2)

Clip _(limit)_ all values of **X** between 0 and 3

In [0]:
mask1 = X < 0
X[mask1] = 0
mask2 = X > 3
X[mask2] = 3
X

tensor([[1, 0, 2],
        [3, 3, 0]])

<div style="background-color:lightblue;padding:1rem;border-radius: 0.015rem 0.015rem 0.03rem 0.03rem;">
<h3 style="display: inline; font-weight:bold"></h3>
</div>

## And many more ...

In [0]:
# press tab to autocomplete
# x.

---

# Tensor Conversions

## Type conversions

The easiest way to cast a Tensor to a different type is to use the `Tensor.to(type)` function.

In [0]:
Y = 4 * torch.rand((2,4))
Y

tensor([[2.7265, 0.6263, 0.2743, 0.3666],
        [1.1418, 0.4325, 1.5740, 0.8671]])

In [0]:
Y.dtype

torch.float32

In [0]:
Y.to(torch.float16) # Check the rounding!

tensor([[2.7266, 0.6265, 0.2744, 0.3667],
        [1.1416, 0.4326, 1.5742, 0.8672]], dtype=torch.float16)

In [0]:
Y.to(torch.int64)

tensor([[2, 0, 0, 0],
        [1, 0, 1, 0]])

In [0]:
Y.to(torch.bool)

tensor([[True, True, True, True],
        [True, True, True, True]])

Note the automatic type promotion :

In [0]:
torch.LongTensor([1, 2]) + torch.FloatTensor([1.1, 2.2])

tensor([2.1000, 4.2000])

## Converting between PyTorch and NumPy

In [0]:
X = np.random.random((5,3))
X

array([[6.85014051e-01, 6.48114171e-02, 1.38500697e-01],
       [2.57416040e-01, 4.01555432e-01, 7.62317018e-01],
       [2.98796849e-01, 8.35883523e-01, 3.78134298e-01],
       [2.02665165e-01, 1.25007607e-01, 6.45879294e-01],
       [1.38446485e-01, 1.45469355e-04, 7.25413036e-01]])

In [0]:
# numpy ---> torch
Y = torch.from_numpy(X)  # Y is actually a DoubleTensor (i.e. 64-bit representation)
Y

tensor([[6.8501e-01, 6.4811e-02, 1.3850e-01],
        [2.5742e-01, 4.0156e-01, 7.6232e-01],
        [2.9880e-01, 8.3588e-01, 3.7813e-01],
        [2.0267e-01, 1.2501e-01, 6.4588e-01],
        [1.3845e-01, 1.4547e-04, 7.2541e-01]], dtype=torch.float64)

In [0]:
Y = torch.rand((2,4))
Y

tensor([[0.0800, 0.6198, 0.1831, 0.2877],
        [0.8353, 0.0981, 0.5795, 0.0496]])

In [0]:
# torch ---> numpy
X = Y.numpy()
X

array([[0.07999748, 0.6198487 , 0.18313593, 0.287745  ],
       [0.8353272 , 0.09813845, 0.5794977 , 0.04959142]], dtype=float32)

## Converting between GPU and CPU

First, you may want to check: 
 - that cuda can actually be used : `torch.cuda.is_available()`
 - how many gpus are available : `torch.cuda.device_count()`

In [0]:
torch.cuda.is_available()

True

In [0]:
torch.cuda.device_count()

1

In [0]:
x = torch.Tensor([[1,2,3], [4,5,6]])
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


### `torch.device`

The best way to easily move a tensor from a device to another is again by using the **`Tensor.to(...)`** function.  
You need to pass as argument a **`torch.device`** object.

A **`torch.device`** is an object representing the device on which a torch.tensor is or will be allocated.

_Note : If you don't have Cuda on the machine, the following examples won't work_

In [0]:
cpu = torch.device('cpu')
cuda_0 = torch.device('cuda:0')

x = x.to(cpu)
print(x.device)
x = x.to(cuda_0)
print(x.device)

cpu
cuda:0


It is flexible since you can check if cuda exists only once in your code. ***Then I will only know if I don't have a GPU because it takes long to run.***

In [0]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
x = x.to(device)  # We don't need to worry anymore about whether cuda is available or not
print(x.device)

cuda:0


### `Tensor.cuda` and `Tensor.cpu`

When you know in advance what device you want to move to, you can use the `Tensor.cuda()` and `Tensor.cpu()` functions.


In [0]:
x = torch.Tensor([[1,2,3], [4,5,6]])
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [0]:
x.cuda()
print(x.device)
x = x.cuda()
print(x.device)
x = x.cuda(0)
print(x.device)
x = x.cpu()
print(x.device)

cuda:0
cuda:0
cuda:0
cpu


In [0]:
x = torch.Tensor([[1,2,3], [4,5,6]])

# This will generate an error since you cannot do operation on tensor that are not on the same device
x + x.cuda()

RuntimeError: ignored

#### Write an if statement that moves x on gpu if cuda is available

In [0]:
# useless

These kinds of if statements used to be all over the place in people's code.  
Now, the more flexible `Tensor.to(...)` function is available and should be used preferably.

### Timing GPU

How much faster is GPU ?  See for yourself ...

In [0]:
A = torch.rand(100, 1000, 1000)
B = A.cuda()
A.size()

torch.Size([100, 1000, 1000])

In [0]:
%timeit -n 3 torch.bmm(A, A)

3 loops, best of 3: 2.36 s per loop


In [0]:
%timeit -n 30 torch.bmm(B, B)

30 loops, best of 3: 18.4 µs per loop


___

<!--NAVIGATION-->
# | Basics | [Autograd >](2-Autograd.ipynb)